export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_ID: 'INVALID_ID',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

export const PROFILE_ERROR_CODES = {
  WRONG_CURRENT_PASSWORD: 'WRONG_CURRENT_PASSWORD',
  SAME_PASSWORD: 'SAME_PASSWORD',
  NOTHING_TO_UPDATE: 'NOTHING_TO_UPDATE',
  USERNAME_CHANGE_TOO_SOON: 'USERNAME_CHANGE_TOO_SOON',
  INVALID_IMAGE: 'INVALID_IMAGE',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  GEOCODER_UNAVAILABLE: 'GEOCODER_UNAVAILABLE',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
};
