export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_ID: 'INVALID_ID',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

export const PROFILE_ERROR_CODES = {
  WRONG_CURRENT_PASSWORD: 'WRONG_CURRENT_PASSWORD',
  SAME_PASSWORD: 'SAME_PASSWORD',
  NOTHING_TO_UPDATE: 'NOTHING_TO_UPDATE',
  USERNAME_CHANGE_TOO_SOON: 'USERNAME_CHANGE_TOO_SOON',
  INVALID_IMAGE: 'INVALID_IMAGE',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  GEOCODER_UNAVAILABLE: 'GEOCODER_UNAVAILABLE',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
};

export const EXPLORE_ERROR_CODES = {
  PLACE_NOT_FOUND: 'PLACE_NOT_FOUND',
  ITINERARY_NOT_FOUND: 'ITINERARY_NOT_FOUND',
  NO_MATCHING_PLACES: 'NO_MATCHING_PLACES',
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  MEDIA_DISABLED: 'MEDIA_DISABLED', // server chưa cấu hình Cloudinary
  MEDIA_INVALID: 'MEDIA_INVALID', // ảnh / video không phải của người đăng, chưa tải xong hoặc vượt giới hạn
  POST_NOT_SHAREABLE: 'POST_NOT_SHAREABLE',
  FRIEND_REQUEST_NOT_FOUND: 'FRIEND_REQUEST_NOT_FOUND',
  ALREADY_FRIENDS: 'ALREADY_FRIENDS',
  FRIEND_REQUEST_EXISTS: 'FRIEND_REQUEST_EXISTS',
  NOT_FRIENDS: 'NOT_FRIENDS',
  CANNOT_FRIEND_SELF: 'CANNOT_FRIEND_SELF',
  TOO_MANY_PENDING_REQUESTS: 'TOO_MANY_PENDING_REQUESTS',
  FORBIDDEN: 'FORBIDDEN',
};
