/**
 * Từ vựng và định nghĩa 11 danh mục địa điểm dành cho Gen Z tại TP.HCM.
 * Phục vụ phân loại dataset, bộ lọc Khám phá và AI Planner.
 */

export const GENZ_CATEGORIES = [
  {
    id: 'games_entertainment',
    name: 'Chơi game & Vui chơi',
    shortName: 'Game & Vui chơi',
    emoji: '🎮',
    badgeClass: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    description: 'Board game, Video game, Arcade, Escape room, VR/AR, Billiard, Bowling, Bắn súng hơi, Trampoline',
    subCategories: [
      { id: 'board_game', name: 'Board game' },
      { id: 'video_game', name: 'Video game / Gaming' },
      { id: 'arcade', name: 'Arcade / Máy gắp thú' },
      { id: 'escape_room', name: 'Escape room (Phòng thoát hiểm)' },
      { id: 'vr_ar', name: 'VR / AR Thực tế ảo' },
      { id: 'billiard', name: 'Billiard / Bida' },
      { id: 'bowling', name: 'Bowling' },
      { id: 'shooting_sport', name: 'Bắn súng hơi / Thể thao mô phỏng' },
      { id: 'trampoline', name: 'Trampoline (Bạt nhún)' },
      { id: 'amusement_park', name: 'Khu vui chơi tổng hợp' },
      { id: 'karaoke', name: 'Karaoke' },
    ],
  },
  {
    id: 'art_creative',
    name: 'Nghệ thuật & Sáng tạo',
    shortName: 'Nghệ thuật & Sáng tạo',
    emoji: '🎨',
    badgeClass: 'bg-rose-50 text-rose-700 border-rose-200',
    description: 'Art gallery, Bảo tàng mỹ thuật, Workshop làm gốm, nến thơm, dệt thảm tufting, vẽ tranh, thủ công',
    subCategories: [
      { id: 'art_gallery', name: 'Art gallery / Phòng tranh' },
      { id: 'museum', name: 'Bảo tàng nghệ thuật' },
      { id: 'pottery_workshop', name: 'Workshop làm gốm' },
      { id: 'tufting_workshop', name: 'Workshop dệt thảm (Tufting)' },
      { id: 'candle_perfume_workshop', name: 'Workshop nến thơm & nước hoa DIY' },
      { id: 'painting_workshop', name: 'Workshop vẽ tranh (Painting)' },
      { id: 'handmade_workshop', name: 'Workshop thủ công / Handmade' },
      { id: 'photography_studio', name: 'Studio chụp ảnh nghệ thuật' },
      { id: 'creative_space', name: 'Không gian sáng tạo' },
    ],
  },
  {
    id: 'music_performance',
    name: 'Âm nhạc & Biểu diễn',
    shortName: 'Âm nhạc & Live',
    emoji: '🎵',
    badgeClass: 'bg-purple-50 text-purple-700 border-purple-200',
    description: 'Live music, Acoustic bar, Jazz club, Kịch nghệ thuật, Open mic, DJ biểu diễn',
    subCategories: [
      { id: 'live_music', name: 'Live music / Nhạc sống' },
      { id: 'acoustic', name: 'Acoustic cafe' },
      { id: 'concert_venue', name: 'Sân khấu biểu diễn / Phòng trà' },
      { id: 'music_bar', name: 'Music bar' },
      { id: 'jazz', name: 'Jazz club' },
      { id: 'theater', name: 'Sân khấu kịch' },
      { id: 'performing_arts', name: 'Nghệ thuật biểu diễn' },
      { id: 'open_mic', name: 'Open mic / Hát giao lưu' },
      { id: 'dj_performance', name: 'DJ show' },
    ],
  },
  {
    id: 'sports_fitness',
    name: 'Thể thao & Vận động',
    shortName: 'Thể thao & Vận động',
    emoji: '⚽',
    badgeClass: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    description: 'Pickleball, Leo núi nhân tạo (Bouldering), Bắn cung, Trượt băng, Cầu lông, Trượt ván',
    subCategories: [
      { id: 'pickleball', name: 'Pickleball' },
      { id: 'rock_climbing', name: 'Leo núi nhân tạo (Bouldering)' },
      { id: 'archery', name: 'Bắn cung' },
      { id: 'ice_skating', name: 'Trượt băng trong nhà' },
      { id: 'badminton', name: 'Cầu lông' },
      { id: 'skating', name: 'Trượt ván / Roller skate' },
      { id: 'gym_yoga', name: 'Gym & Yoga' },
      { id: 'swimming', name: 'Bơi lội' },
      { id: 'cycling', name: 'Đạp xe dã ngoại' },
    ],
  },
  {
    id: 'nature_outdoors',
    name: 'Thiên nhiên & Ngoài trời',
    shortName: 'Thiên nhiên & Chill',
    emoji: '🌳',
    badgeClass: 'bg-teal-50 text-teal-700 border-teal-200',
    description: 'Công viên ven sông, Nóc hầm Thủ Thiêm, Bến Bạch Đằng, Hồ Con Rùa, Picnic, Ngắm hoàng hôn',
    subCategories: [
      { id: 'riverside', name: 'Công viên bờ sông / Bến tàu thủy' },
      { id: 'sunset_spot', name: 'Điểm ngắm hoàng hôn' },
      { id: 'park', name: 'Công viên cây xanh' },
      { id: 'walking_street', name: 'Phố đi bộ ven sông' },
      { id: 'camping_picnic', name: 'Camping / Picnic dã ngoại' },
      { id: 'outdoor_chill', name: 'Điểm chill ngoài trời' },
    ],
  },
  {
    id: 'cafe_social',
    name: 'Cà phê & Giao lưu',
    shortName: 'Cafe & Check-in',
    emoji: '☕',
    badgeClass: 'bg-amber-50 text-amber-700 border-amber-200',
    description: 'Specialty coffee, Cà phê thú cưng, Cafe núp hẻm hoài cổ, Cà phê cú đêm 24/7 chạy deadline, Rooftop cafe',
    subCategories: [
      { id: 'specialty_coffee', name: 'Specialty coffee' },
      { id: 'pet_cafe', name: 'Cà phê thú cưng (Mèo, Chó, Capybara)' },
      { id: 'study_cafe_24h', name: 'Cà phê 24/7 / Chạy deadline' },
      { id: 'hidden_alley_cafe', name: 'Cà phê núp hẻm / Chung cư cổ' },
      { id: 'themed_cafe', name: 'Cà phê concept chụp ảnh' },
      { id: 'rooftop_cafe', name: 'Rooftop cafe ngắm view' },
      { id: 'dessert_cafe', name: 'Tiệm bánh & tráng miệng' },
      { id: 'social_space', name: 'Không gian giao lưu cộng đồng' },
    ],
  },
  {
    id: 'shopping_lifestyle',
    name: 'Mua sắm & Khám phá',
    shortName: 'Local Brand & Chợ Phiên',
    emoji: '🛍️',
    badgeClass: 'bg-pink-50 text-pink-700 border-pink-200',
    description: 'Tổ hợp thời trang Local brand, Chợ phiên Flea market, Tiệm đồ si vintage, Concept store, Đường sách',
    subCategories: [
      { id: 'local_brand_complex', name: 'Tổ hợp thời trang Local brand' },
      { id: 'flea_market', name: 'Chợ phiên Flea market cuối tuần' },
      { id: 'vintage_thrift', name: 'Tiệm đồ si / Vintage store' },
      { id: 'concept_store', name: 'Concept store độc bản' },
      { id: 'bookstore', name: 'Đường sách / Nhà sách phong cách' },
      { id: 'lifestyle_store', name: 'Tiệm phụ kiện & đời sống' },
    ],
  },
  {
    id: 'cinema_immersive',
    name: 'Xem & Trải nghiệm',
    shortName: 'Triển lãm & Trải nghiệm',
    emoji: '🎬',
    badgeClass: 'bg-cyan-50 text-cyan-700 border-cyan-200',
    description: 'Triển lãm đa giác quan (Immersive art), Rạp chiếu phim 270 độ / phòng đôi, Thủy cung, Trải nghiệm số',
    subCategories: [
      { id: 'immersive_exhibition', name: 'Triển lãm đa giác quan (Immersive)' },
      { id: 'digital_art', name: 'Nghệ thuật thị giác số / Mixed Reality' },
      { id: 'cinema_experience', name: 'Rạp chiếu công nghệ cao / Rạp giường nằm' },
      { id: 'aquarium', name: 'Thủy cung' },
      { id: 'interactive_museum', name: 'Bảo tàng tương tác' },
      { id: 'theme_experience', name: 'Khu trải nghiệm theo chủ đề' },
    ],
  },
  {
    id: 'nightlife',
    name: 'Vui chơi ban đêm',
    shortName: 'Về đêm & Chill bar',
    emoji: '🌙',
    badgeClass: 'bg-blue-50 text-blue-700 border-blue-200',
    description: 'Phố đi bộ đêm, Chợ ẩm thực đêm, Speakeasy bar ẩn mình, Rooftop bar ngắm Landmark, Quán ốc đêm',
    subCategories: [
      { id: 'night_street', name: 'Phố đi bộ đêm / Phố Tây' },
      { id: 'night_food_street', name: 'Phố ẩm thực đêm / Phố ốc' },
      { id: 'night_market', name: 'Chợ đêm' },
      { id: 'speakeasy_bar', name: 'Speakeasy bar (Bar ẩn mình)' },
      { id: 'rooftop_bar', name: 'Rooftop bar ngắm thành phố' },
      { id: 'late_night_hangout', name: 'Tụ điểm chill đêm' },
    ],
  },
  {
    id: 'discovery_hidden',
    name: 'Khám phá',
    shortName: 'Khám phá & Check-in',
    emoji: '🗺️',
    badgeClass: 'bg-orange-50 text-orange-700 border-orange-200',
    description: 'Hẻm cổ người Hoa, Phố Nhật bí mật, Chùa kiến trúc độc đáo, Cư xá retro, Hidden gem ít người biết',
    subCategories: [
      { id: 'hidden_gem', name: 'Hidden gem (Địa điểm bí mật)' },
      { id: 'local_heritage', name: 'Hẻm cổ / Khu phố văn hóa lịch sử' },
      { id: 'unique_architecture', name: 'Kiến trúc tôn giáo / Nghệ thuật độc lạ' },
      { id: 'street_food_alley', name: 'Hẻm ẩm thực địa phương' },
      { id: 'retro_apartment', name: 'Cư xá cổ / Không gian hoài niệm' },
    ],
  },
  {
    id: 'learning_workshop',
    name: 'Học tập & Trải nghiệm',
    shortName: 'Workshop & Kỹ năng',
    emoji: '📚',
    badgeClass: 'bg-lime-50 text-lime-700 border-lime-200',
    description: 'Lớp học nấu ăn truyền thống, Art hub, Coworking space tri thức, Câu lạc bộ sách, Giao lưu ngoại ngữ',
    subCategories: [
      { id: 'cooking_class', name: 'Lớp học nấu ăn & làm bánh' },
      { id: 'art_hub', name: 'Không gian ươm mầm nghệ thuật' },
      { id: 'coworking_study', name: 'Không gian làm việc & học tập' },
      { id: 'book_club', name: 'Tiệm sách & CLB trao đổi sách' },
      { id: 'language_exchange', name: 'Giao lưu ngôn ngữ / CLB văn hóa' },
      { id: 'skill_workshop', name: 'Workshop kỹ năng sống & phát triển bản thân' },
    ],
  },
];

export const GENZ_CATEGORY_IDS = GENZ_CATEGORIES.map((c) => c.id);

export const TIKTOK_VIRAL_LEVELS = ['viral', 'trending', 'popular', 'rising'];

export const EXPERIENCE_SETTINGS = ['indoor', 'outdoor', 'hybrid'];

export const SUITABLE_AUDIENCE = ['friend_group', 'couple', 'solo', 'study'];

export const TIME_SUITABILITY = ['daytime', 'evening', 'late_night', 'all_day'];
